### PR TITLE
Bring dev tools up to par with httpx

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
Fix some typing and linting errors as a result.

### CODE REVIEW

**Comment by yeraydiazdiaz** [comment]
@tomchristie looks like Travis not enabled for httpcore on PRs? I can't see anything different from httpx in `.travis.yml`...

**Comment by tomchristie** [comment]
@yeraydiazdiaz I think there may be an issue with them reporting to GitHub at the moment.

https://travis-ci.org/github/encode/httpcore/pull_requests

**Comment by tomchristie** [comment]
Thanks @yeraydiazdiaz!

**Comment by yeraydiazdiaz** [comment]
No worries! Is it ok to merged this?

I think `httpcore` is not set to require a review unlike httpx, maybe we should add that too.

**Comment by yeraydiazdiaz** [comment]
Woops 😂 I think I clicked the wrong button. Hope that's ok... 😅

**Pull request merged**
