### PR TITLE
Made ConnectionPool interface private

### PR DESCRIPTION
**Pull request by victoraugustolls**
Made ConnectionPool interface private, except .request and .aclose /.close

This addresses some comments in #18, but is missing `get_connection_stats()`

Update:

Added naive implementation to `get_connection_stats()`, will change if necessary!
Added only one test case for it, but if needed I can make more.

### CODE REVIEW

**Comment by tomchristie** [comment]
Ah fantastic stuff thanks!

I'd probably suggest that we drop the `get_connection_stats` from this PR, and split that into an isolated issue, so that we can discuss it independantly without blocking the "make the interfaces private" part of this?

**Comment by victoraugustolls** [comment]
Will do!

**Comment by victoraugustolls** [comment]
@tomchristie done!

**Comment by tomchristie** [comment]
Great thanks! Let's get this one in.

**Pull request merged**
