### PR TITLE
Version 0.17.3

### PR DESCRIPTION
**Pull request by karosis88**
## TODO

- [x] Add a release date to the changelog.

## 0.17.3

- The networking backend interface has [been added to the public API](https://www.encode.io/httpcore/network-backends). Some classes which were previously private implementation detail are now part of the top-level public API. (#699)
- Support async cancellations, ensuring that the connection pool is left in a clean state when cancellations occur. (#726)
- Graceful handling of HTTP/2 GoAway frames, with requests being transparently retried on a new connection. (#730)
- Add exceptions when a synchronous `trace callback` is passed to an asynchronous request or an asynchronous `trace callback` is passed to a synchronous request. (#717)

### CODE REVIEW

**Comment by karosis88** [comment]
I noticed that there was no `httpcore` release in July, so this is the first one :-)
We can also include #726 in this release because `httpx` has many issues with #726.

**Comment by karosis88** [comment]
Is there anything else we'd like to see in this release?

**Comment by tomchristie** [comment]
> Is there anything else we'd like to see in this release?

No I think this is a good cutting point. `<snip>`

**Comment by tomchristie** [comment]
I have a release draft here... https://github.com/encode/httpcore/releases/tag/untagged-1c6e6829784084137660
Which I've dated ready for a release tomorrow.

Does that all look correct to you?

**Comment by karosis88** [comment]
Yes, this appears to be correct to me. Should I include the date in the changelog?

**Comment by tomchristie** [comment]
Yep.

**Review by tomchristie — APPROVED** [review]

**Pull request merged**
