### PR TITLE
Add test for write timeout error

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
Inching closer to #26

### CODE REVIEW

**Comment by tomchristie** [comment]
Looks nice! Does this fail locally? Not currently failing on travis. More complex interaction on the write timeout than other cases, since deps on write buffer sizes and stuff. Cheap lazy approach here could just be to whack up the amount of data written 10x and see if that reliably works. Alternatively we might need to dig into setting the buffer limits explicitly, either here, or in the Uvicorn server that’s ingesting the data. Or something. 😝

**Comment by tomchristie** [comment]
Running this locally I can see it passes on my machine too.
Have bumped up the amount of data 10x to see if that triggers the case on travis too.

**Comment by tomchristie** [comment]
Ahhhahahahhahahahah

Screenshot 2019-05-16 at 11 00 00

**Comment by tomchristie** [comment]
Oh yas 😝

**Comment by yeraydiazdiaz** [comment]
So close!! 😄

**Pull request merged**
