### PR TITLE
Add logger trace

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
Closes https://github.com/encode/httpcore/issues/58

I tried to replicate the calls we used to have in httpx, may have missed some but we can just add them as needed moving forward.

### CODE REVIEW

**Comment by yeraydiazdiaz** [comment]
Just thought we may want to consider matching `HTTPCORE_LOG_LEVEL` to `HTTPX_LOG_LEVEL` to make things slightly more convenient.

**Comment by tomchristie** [comment]
Yeah either that or support both?

**Comment by tomchristie** [comment]
I guess we could have httpx set HTTPCORE_LOG_LEVEL if needed, but maybe that’s overdoing it a bit.

**Comment by yeraydiazdiaz** [comment]
I'd say support both makes more sense, I'll add that.

**Comment by yeraydiazdiaz** [comment]
Thanks! 🚀

**Comment by tomchristie** [comment]
👍- 0.8.4 Release PR welcome at this point then, I guess?

**Comment by yeraydiazdiaz** [comment]
Yup, I can put that together 👍

**Pull request merged**
