### PR TITLE
Pin sortedcontainers version to avoid requirements' installation error

### PR DESCRIPTION
**Pull request by cdeler**

### CODE REVIEW

**Comment by tomchristie** [comment]
Thanks. I'm not seeing the issue here that's causing you to have to pin this.
Afterall, our CI seem to be running just fine at the moment, installing from `requirements.txt`.
Eg. https://github.com/encode/httpcore/pull/153/checks?check_run_id=973082003

Any thoughts?

**Comment by jcugat** [comment]
@tomchristie it's not an error per se (execution finishes successfully), but it also happens in CI:

image

**Comment by jcugat** [comment]
By the way, testing this with the new pip resolver works correctly without any error message:

<details>
  <summary>Click to expand!</summary>
  
```
[23:28:54] nova@lighty:~/w/httpcore> pip install --use-feature=2020-resolver -r requirements.txt
Obtaining file:///Users/nova/workspace/httpcore (from -r requirements.txt (line 1))
Requirement already satisfied: wheel in /Users/nova/.pyenv/versions/3.8.2/envs/httpcore/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (0.34.2)
Collecting sniffio==1.*
  Using cached sniffio-1.1.0-py3-none-any.whl (4.5 kB)
Collecting h11<0.10,>=0.8
  Using cached h11-0.9.0-py2.py3-none-any.whl (53 kB)
Collecting trio-typing
  Using cached trio_typing-0.5.0-py3-none-any.whl (40 kB)
Collecting trio
  Using cached trio-0.16.0-py3-none-any.whl (337 kB)
Collecting mypy-extensions>=0.4.2
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting attrs>=19.2.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting async-generator>=1.9
  Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Collecting mypy
  Using cached mypy-0.782-cp38-cp38-macosx_10_9_x86_64.whl (8.8 MB)
Processing /Users/nova/Library/Caches/pip/wheels/90/d4/0c/d1e5fbaba4f3eef9ced2a95737b027aca1a5ea7e52e490f3b2/typed_ast-1.4.1-cp38-cp38-macosx_10_14_x86_64.whl
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Collecting outcome
  Using cached outcome-1.0.1-py2.py3-none-any.whl (10 kB)
Processing /Users/nova/Library/Caches/pip/wheels/52/a3/bc/a7a20080fadc1f69d737caa6facf3434270b6d6162b1fc4ba8/mkautodoc-0.1.0-py3-none-any.whl
Collecting h2==3.*
  Using cached h2-3.2.0-py2.py3-none-any.whl (65 kB)
Collecting hyperframe<6,>=5.2.0
  Using cached hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Collecting hpack<4,>=3.0
  Using cached hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Collecting trustme
  Using cached trustme-0.6.0-py2.py3-none-any.whl (14 kB)
Collecting pytest-trio
  Using cached pytest_trio-0.6.0-py3-none-any.whl (25 kB)
Collecting pytest-asyncio
  Using cached pytest_asyncio-0.14.0-py3-none-any.whl (11 kB)
Collecting pytest
  Using cached pytest-6.0.1-py3-none-any.whl (270 kB)
Collecting py>=1.8.2
  Using cached py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting iniconfig
  Using cached iniconfig-1.0.1-py3-none-any.whl (4.2 kB)
Collecting toml
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting more-itertools>=4.0.0
  Using cached more_itertools-8.4.0-py3-none-any.whl (43 kB)
Collecting black
  Using cached black-19.10b0-py36-none-any.whl (97 kB)
Collecting pathspec<1,>=0.6
  Using cached pathspec-0.8.0-py2.py3-none-any.whl (28 kB)
Collecting click>=6.5
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting isort==5.*
  Using cached isort-5.3.2-py3-none-any.whl (93 kB)
Collecting idna
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting packaging
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Processing /Users/nova/Library/Caches/pip/wheels/ec/bc/11/2715121b764b496897ebe07883139ea07aa780711394e931fe/autoflake-1.3.1-py3-none-any.whl
Collecting pyflakes>=1.1.0
  Using cached pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting twine
  Using cached twine-3.2.0-py3-none-any.whl (34 kB)
Requirement already satisfied: setuptools>=0.7.0 in /Users/nova/.pyenv/versions/3.8.2/envs/httpcore/lib/python3.8/site-packages (from twine->-r requirements.txt (line 13)) (49.3.1)
Collecting rfc3986>=1.4.0
  Using cached rfc3986-1.4.0-py2.py3-none-any.whl (31 kB)
Collecting colorama>=0.4.3
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting requests-toolbelt!=0.9.0,>=0.8.0
  Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting pkginfo>=1.4.2
  Using cached pkginfo-1.5.0.1-py2.py3-none-any.whl (25 kB)
Collecting requests>=2.20
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting readme-renderer>=21.0
  Using cached readme_renderer-26.0-py2.py3-none-any.whl (15 kB)
Collecting Pygments>=2.5.1
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Collecting docutils>=0.13.1
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Collecting bleach>=2.1.0
  Using cached bleach-3.1.5-py2.py3-none-any.whl (151 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting keyring>=15.1
  Using cached keyring-21.3.0-py3-none-any.whl (31 kB)
Collecting pytest-cov
  Using cached pytest_cov-2.10.0-py2.py3-none-any.whl (19 kB)
Collecting coverage>=4.4
  Using cached coverage-5.2.1-cp38-cp38-macosx_10_9_x86_64.whl (205 kB)
Collecting sortedcontainers
  Using cached sortedcontainers-2.2.2-py2.py3-none-any.whl (29 kB)
Collecting mitmproxy
  Using cached mitmproxy-5.2-py3-none-any.whl (1.4 MB)
Collecting sortedcontainers
  Using cached sortedcontainers-2.1.0-py2.py3-none-any.whl (28 kB)
Collecting pyOpenSSL<19.2,>=19.1.0
  Using cached pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
Collecting blinker<1.5,>=1.4
  Using cached blinker-1.4.tar.gz (111 kB)
Collecting urwid!=2.1.0,==2.0.1
  Using cached urwid-2.0.1.tar.gz (604 kB)
Collecting kaitaistruct<0.9,>=0.7
  Using cached kaitaistruct-0.8.tar.gz (5.2 kB)
Collecting ldap3<2.8,>=2.6.1
  Using cached ldap3-2.7-py2.py3-none-any.whl (420 kB)
Collecting flask<1.2,>=1.1.1
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting itsdangerous>=0.24
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting cryptography
  Using cached cryptography-2.9.2-cp35-abi3-macosx_10_9_x86_64.whl (1.8 MB)
Collecting wsproto<0.16,>=0.14
  Using cached wsproto-0.15.0-py2.py3-none-any.whl (24 kB)
Collecting publicsuffix2<3,>=2.20190812
  Using cached publicsuffix2-2.20191221-py2.py3-none-any.whl (89 kB)
Collecting Brotli<1.1,>=1.0
  Using cached Brotli-1.0.7-cp38-cp38-macosx_10_9_x86_64.whl (412 kB)
Collecting zstandard<0.14,>=0.11
  Using cached zstandard-0.13.0-cp38-cp38-macosx_10_9_x86_64.whl (460 kB)
Collecting passlib<1.8,>=1.6.5
  Using cached passlib-1.7.2-py2.py3-none-any.whl (507 kB)
Collecting Jinja2>=2.10.1
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (16 kB)
Collecting pyperclip<1.9,>=1.6.0
  Using cached pyperclip-1.8.0.tar.gz (16 kB)
Collecting ruamel.yaml<0.17,>=0.16
  Using cached ruamel.yaml-0.16.10-py2.py3-none-any.whl (111 kB)
Collecting ruamel.yaml.clib>=0.1.2
  Using cached ruamel.yaml.clib-0.2.0.tar.gz (178 kB)
Collecting Werkzeug>=0.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting protobuf<3.12,>=3.6.0
  Using cached protobuf-3.11.3-cp38-cp38-macosx_10_9_x86_64.whl (1.3 MB)
Requirement already satisfied: setuptools>=0.7.0 in /Users/nova/.pyenv/versions/3.8.2/envs/httpcore/lib/python3.8/site-packages (from twine->-r requirements.txt (line 13)) (49.3.1)
Collecting pyasn1<0.5,>=0.3.1
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Processing /Users/nova/Library/Caches/pip/wheels/88/79/e5/598ba17e85eccf2626eab62e4ee8452895636cd542650d450d/tornado-6.0.4-cp38-cp38-macosx_10_14_x86_64.whl
Collecting cffi!=1.11.3,>=1.8
  Using cached cffi-1.14.1-cp38-cp38-macosx_10_9_x86_64.whl (176 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting mkdocs
  Using cached mkdocs-1.1.2-py3-none-any.whl (6.4 MB)
Collecting lunr[languages]==0.5.8
  Using cached lunr-0.5.8-py2.py3-none-any.whl (2.3 MB)
Collecting Markdown>=3.2.1
  Using cached Markdown-3.2.2-py3-none-any.whl (88 kB)
Processing /Users/nova/Library/Caches/pip/wheels/27/9e/9b/1509419d1fc2dc8f84375252a765019a46d45c63f83b33a020/livereload-2.6.2-py2.py3-none-any.whl
Processing /Users/nova/Library/Caches/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4/future-0.18.2-py3-none-any.whl
Processing /Users/nova/Library/Caches/pip/wheels/ff/d5/7b/f1fb4e1e1603b2f01c2424dd60fbcc50c12ef918bafc44b155/nltk-3.5-py3-none-any.whl
Processing /Users/nova/Library/Caches/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c/PyYAML-5.3.1-cp38-cp38-macosx_10_14_x86_64.whl
Collecting joblib
  Using cached joblib-0.16.0-py3-none-any.whl (300 kB)
Collecting tqdm>=4.14
  Using cached tqdm-4.48.2-py2.py3-none-any.whl (68 kB)
Collecting uvicorn
  Using cached uvicorn-0.11.8-py3-none-any.whl (43 kB)
Collecting uvloop>=0.14.0
  Using cached uvloop-0.14.0-cp38-cp38-macosx_10_11_x86_64.whl (1.5 MB)
Collecting httptools==0.1.*
  Using cached httptools-0.1.1-cp38-cp38-macosx_10_13_x86_64.whl (102 kB)
Collecting websockets==8.*
  Using cached websockets-8.1-cp38-cp38-macosx_10_9_x86_64.whl (64 kB)
Collecting mkdocs-material
  Using cached mkdocs_material-5.5.5-py2.py3-none-any.whl (3.8 MB)
Collecting mkdocs-material-extensions>=1.0
  Using cached mkdocs_material_extensions-1.0-py3-none-any.whl (7.9 kB)
Collecting pymdown-extensions>=7.0
  Using cached pymdown_extensions-8.0-py2.py3-none-any.whl (206 kB)
Collecting regex
  Using cached regex-2020.7.14.tar.gz (690 kB)
Building wheels for collected packages: blinker, urwid, kaitaistruct, pyperclip, ruamel.yaml.clib, regex
  Building wheel for blinker (setup.py) ... done
  Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13452 sha256=27720bf6a49fa7c16a033a39fa34e818f09428bb1b4785af67947b2c1ad963ec
  Stored in directory: /Users/nova/Library/Caches/pip/wheels/b7/a5/68/fe632054a5eadd531c7a49d740c50eb6adfbeca822b4eab8d4
  Building wheel for urwid (setup.py) ... done
  Created wheel for urwid: filename=urwid-2.0.1-cp38-cp38-macosx_10_14_x86_64.whl size=229491 sha256=94d145324b54bf18430008d784331af118c80234292723a7d9dd9d6743b2de6f
  Stored in directory: /Users/nova/Library/Caches/pip/wheels/b6/bf/68/3fccbd1a17b713fcca4eefde6475777f749f3b8ea21f2c5eb3
  Building wheel for kaitaistruct (setup.py) ... done
  Created wheel for kaitaistruct: filename=kaitaistruct-0.8-py2.py3-none-any.whl size=4922 sha256=21d783c8315021fc3947b4460f22b625707a9143fe4ae417e6e81f6d145e41cc
  Stored in directory: /Users/nova/Library/Caches/pip/wheels/21/9e/07/4a48aca3de6d2402327907029503e072ad90737ec443cdbc41
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.0-py3-none-any.whl size=8691 sha256=a497ad8ef592f5a257ffb2b9a7e55ab2f1789f10211f910943c3a39b1a04688a
  Stored in directory: /Users/nova/Library/Caches/pip/wheels/03/79/58/ab51f0f590281b0f4f6046d9271eb98cc50565afb9200f155a
  Building wheel for ruamel.yaml.clib (setup.py) ... done
  Created wheel for ruamel.yaml.clib: filename=ruamel.yaml.clib-0.2.0-cp38-cp38-macosx_10_14_x86_64.whl size=155794 sha256=b6b86bc08d269f639d146ddbf836b8928ef15d121923968ff8953f5f88d6f755
  Stored in directory: /Users/nova/Library/Caches/pip/wheels/e4/3e/eb/975034325f52bc0d5897b5f8603974d6a79a964aaeb0ec0293
  Building wheel for regex (setup.py) ... done
  Created wheel for regex: filename=regex-2020.7.14-cp38-cp38-macosx_10_14_x86_64.whl size=284603 sha256=d985307352a621cae61effebc6541507a328441326d80453e6a7e08299e78899
  Stored in directory: /Users/nova/Library/Caches/pip/wheels/c1/d2/6f/d7db2c6251fdcb9371d7d966eaddf630ac4e375f24252de399
Successfully built blinker urwid kaitaistruct pyperclip ruamel.yaml.clib regex
Installing collected packages: tqdm, six, regex, pyparsing, pycparser, joblib, future, click, webencodings, urllib3, tornado, packaging, nltk, MarkupSafe, lunr, idna, chardet, cffi, certifi, attrs, Werkzeug, typing-extensions, typed-ast, toml, sortedcontainers, sniffio, ruamel.yaml.clib, requests, PyYAML, Pygments, pyasn1, py, pluggy, outcome, mypy-extensions, more-itertools, Markdown, livereload, Jinja2, itsdangerous, iniconfig, hyperframe, hpack, h11, docutils, cryptography, bleach, async-generator, zstandard, wsproto, websockets, uvloop, urwid, trio, ruamel.yaml, rfc3986, requests-toolbelt, readme-renderer, pytest, pyperclip, pyOpenSSL, pymdown-extensions, pyflakes, publicsuffix2, protobuf, pkginfo, pathspec, passlib, mypy, mkdocs-material-extensions, mkdocs, ldap3, keyring, kaitaistruct, httptools, httpcore, h2, flask, coverage, colorama, Brotli, blinker, appdirs, uvicorn, twine, trustme, trio-typing, pytest-trio, pytest-cov, pytest-asyncio, mkdocs-material, mkautodoc, mitmproxy, isort, black, autoflake
  Running setup.py develop for httpcore
Successfully installed Brotli-1.0.7 Jinja2-2.11.2 Markdown-3.2.2 MarkupSafe-1.1.1 PyYAML-5.3.1 Pygments-2.6.1 Werkzeug-1.0.1 appdirs-1.4.4 async-generator-1.10 attrs-19.3.0 autoflake-1.3.1 black-19.10b0 bleach-3.1.5 blinker-1.4 certifi-2020.6.20 cffi-1.14.1 chardet-3.0.4 click-7.1.2 colorama-0.4.3 coverage-5.2.1 cryptography-2.9.2 docutils-0.16 flask-1.1.2 future-0.18.2 h11-0.9.0 h2-3.2.0 hpack-3.0.0 httpcore httptools-0.1.1 hyperframe-5.2.0 idna-2.10 iniconfig-1.0.1 isort-5.3.2 itsdangerous-1.1.0 joblib-0.16.0 kaitaistruct-0.8 keyring-21.3.0 ldap3-2.7 livereload-2.6.2 lunr-0.5.8 mitmproxy-5.2 mkautodoc-0.1.0 mkdocs-1.1.2 mkdocs-material-5.5.5 mkdocs-material-extensions-1.0 more-itertools-8.4.0 mypy-0.782 mypy-extensions-0.4.3 nltk-3.5 outcome-1.0.1 packaging-20.4 passlib-1.7.2 pathspec-0.8.0 pkginfo-1.5.0.1 pluggy-0.13.1 protobuf-3.11.3 publicsuffix2-2.20191221 py-1.9.0 pyOpenSSL-19.1.0 pyasn1-0.4.8 pycparser-2.20 pyflakes-2.2.0 pymdown-extensions-8.0 pyparsing-2.4.7 pyperclip-1.8.0 pytest-6.0.1 pytest-asyncio-0.14.0 pytest-cov-2.10.0 pytest-trio-0.6.0 readme-renderer-26.0 regex-2020.7.14 requests-2.24.0 requests-toolbelt-0.9.1 rfc3986-1.4.0 ruamel.yaml-0.16.10 ruamel.yaml.clib-0.2.0 six-1.15.0 sniffio-1.1.0 sortedcontainers-2.1.0 toml-0.10.1 tornado-6.0.4 tqdm-4.48.2 trio-0.16.0 trio-typing-0.5.0 trustme-0.6.0 twine-3.2.0 typed-ast-1.4.1 typing-extensions-3.7.4.2 urllib3-1.25.10 urwid-2.0.1 uvicorn-0.11.8 uvloop-0.14.0 webencodings-0.5.1 websockets-8.1 wsproto-0.15.0 zstandard-0.13.0
```
</details>

**Comment by cdeler** [comment]
> it's not an error per se (execution finishes successfully), but it also happens in CI
return code == 0, but the message highlighted by red in console

To avoid such errors I use `poetry` on my work, but it's nice that `pip` introduces the resolver

**Comment by florimondmanca** [comment]
> By the way, testing this with the new pip resolver works correctly without any error message:

@jcugat Are you saying that without the change from this PR, using `--use-feature=2020-resolver` (or setting `PIP_USE_FEATURE=2020-resolver` as an env var, which I've personally done in my shell startup script) fixes the issue?

**Comment by jcugat** [comment]
@florimondmanca yes, if you expand the logs I attached before, you can see that pip initially downloads `sortedcontainers-2.2.2-py2.py3-none-any.whl` but then it changes to `sortedcontainers-2.1.0-py2.py3-none-any.whl` which is the correct version to use.

**Comment by jcugat** [comment]
I still think that we should pin **all** development dependencies to strict versions ([as I commented before](https://github.com/encode/httpx/pull/1053#issuecomment-653910614)), and let dependabot bump those. You can check my test of this in the fork of httpx where I enabled it: https://github.com/jcugat/httpx/pulls

**Comment by cdeler** [comment]
I tried to resolve all dev dependencies using `pip-tools`
1. I created `requirements.dev.in`:
```
# Optionals
trio
trio-typing

# Docs
mkdocs
mkautodoc
mkdocs-material

# Packaging
twine
wheel

# Tests & Linting
pytest
pytest-asyncio
pytest-trio
pytest-cov
black
autoflake
mypy
isort==5.*
mitmproxy
trustme
uvicorn
```

2. Then ran `pip-tools` and got the resolved dependencies:
```bash
(venv-httpcore) ~/workspace/skv/httpcore % pip-compile -U --no-header --no-annotate --rebuild --dry-run requirements.dev.in
appdirs==1.4.4
async-generator==1.10
attrs==19.3.0
autoflake==1.3.1
black==19.10b0
bleach==3.1.5
blinker==1.4
brotli==1.0.7
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
click==7.1.2
colorama==0.4.3
coverage==5.2.1
cryptography==2.9.2
docutils==0.16
flask==1.1.2
future==0.18.2
h11==0.9.0
h2==3.2.0
hpack==3.0.0
httptools==0.1.1
hyperframe==5.2.0
idna==2.10
iniconfig==1.0.1
isort==5.3.2
itsdangerous==1.1.0
jinja2==2.11.2
joblib==0.16.0
kaitaistruct==0.8
keyring==21.3.0
ldap3==2.7
livereload==2.6.2
lunr[languages]==0.5.8
markdown==3.2.2
markupsafe==1.1.1
mitmproxy==5.2
mkautodoc==0.1.0
mkdocs-material-extensions==1.0
mkdocs-material==5.5.6
mkdocs==1.1.2
more-itertools==8.4.0
mypy-extensions==0.4.3
mypy==0.782
nltk==3.5
outcome==1.0.1
packaging==20.4
passlib==1.7.2
pathspec==0.8.0
pkginfo==1.5.0.1
pluggy==0.13.1
protobuf==3.11.3
publicsuffix2==2.20191221
py==1.9.0
pyasn1==0.4.8
pycparser==2.20
pyflakes==2.2.0
pygments==2.6.1
pymdown-extensions==8.0
pyopenssl==19.1.0
pyparsing==2.4.7
pyperclip==1.8.0
pytest-asyncio==0.14.0
pytest-cov==2.10.0
pytest-trio==0.6.0
pytest==6.0.1
pyyaml==5.3.1
readme-renderer==26.0
regex==2020.7.14
requests-toolbelt==0.9.1
requests==2.24.0
rfc3986==1.4.0
ruamel.yaml.clib==0.2.0
ruamel.yaml==0.16.10
six==1.15.0
sniffio==1.1.0
sortedcontainers==2.1.0
toml==0.10.1
tornado==6.0.4
tqdm==4.48.2
trio-typing==0.5.0
trio==0.16.0
trustme==0.6.0
twine==3.2.0
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.10
urwid==2.0.1
uvicorn==0.11.8
uvloop==0.14.0
webencodings==0.5.1
websockets==8.1
werkzeug==1.0.1
wheel==0.34.2
wsproto==0.15.0
zstandard==0.13.0

# The following packages are considered to be unsafe in a requirements file:
# setuptools
Dry-run, so nothing updated.
```
3. Having updated the requirement with the above 3p depts, I tested the installation locally. It worked without warnings

**Comment by florimondmanca** [comment]
@jcugat The Dependabot PRs in your fork look pretty good. I'd be interested we try this in either HTTPCore and HTTPX, then expand to both if it works well. WDYT?

**Comment by florimondmanca** [comment]
Gently closing this in favor of #163 which enables the pip resolver when working on this repo. Thanks for the time put into this @cdeler!

**Pull request closed without merging**
