### PR TITLE
Add test to https server

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
Add `https_server` test fixture.

The self-signed certificate was created using [these steps](https://devcenter.heroku.com/articles/ssl-certificate-self).

### CODE REVIEW

**Comment by yeraydiazdiaz** [comment]
In terms of test coverage, there are paths which are only hit with an appropriately signed certificate, not sure how we'd like to address that to achieve 100%.

**Comment by tomchristie** [comment]
How long is the cert signed for here?

**Comment by pquentin** [comment]
For signed certificates, I would suggest using https://github.com/python-trio/trustme. We use this in urllib3 and it works well. For bonus points, generate new certs/keys dynamically in the tests, which is possible since trustme is written in Python. It avoids storing blobs in the test suite.

**Comment by tomchristie** [comment]
Oh nice! Great tip!

**Comment by yeraydiazdiaz** [comment]
Updated with `trustme` much cleaner, thanks @pquentin!

**Comment by tomchristie** [comment]
Great stuff. 😎

**Pull request merged**
