### PR TITLE
Add badges to README

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
Closes https://github.com/encode/httpcore/issues/64

### CODE REVIEW

**Comment by tomchristie** [comment]
Great! I guess let's have the badges on the `docs/index.md` too?

**Comment by tomchristie** [comment]
Related to this: Occurred to me that the Test Suite badge probably *isn't actually* giving us the "show the results of the latest merge to master".

We might need to switch the config so that we *are* building again on the final commit to master? (Right now we're only building against PRs, and have enforced the "PRs must be up to date with master setting") so that the badges are actually reflecting the status of PRs once commited?

**Comment by yeraydiazdiaz** [comment]
Personally I don't mind, but I guess it might be confusing for people clicking on that link and not seeing `master` which could lead to some unnecessary interaction.

**Comment by tomchristie** [comment]
> Personally I don't mind, but I guess it might be confusing for people clicking on that link and not seeing master which could lead to some unnecessary interaction.

It's not the link that's an issue, so much as the badge colour / status check. Right now, I'm not sure it'll even be getting updated, since it's a badge based on "default branch", that's only running against PRs (not the final merge-to-master), and the PRs themselves are never *on* master branch.

It's just not clear to me if the badge behaviour with our current config *is* actually meaningful.

**Pull request merged**
