### PR TITLE
Version 0.8.0

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
### Fixed

- Fixed tunnel proxy support.

### Added

- New `TimeoutException` base class.

### CODE REVIEW

**Comment by tomchristie** [comment]
Hrm, would be nice if there was an obvious way to bump these into running...

Screenshot 2020-04-30 at 10 53 14

**Comment by yeraydiazdiaz** [comment]
Did you trigger those manually? I couldn't find a way to do it...

**Comment by tomchristie** [comment]
> Did you trigger those manually? I couldn't find a way to do it...

I happened to update the changelog.

Will give GitHub some leeway here, and see if things settle down. Could be something like slowly ramping up action limits on the encode repo.

**Comment by yeraydiazdiaz** [comment]
https://pypi.org/project/httpcore/ 🎉 

Seems the docs build failed though...

**Comment by tomchristie** [comment]
Yup, failed to import `httpcore` for the autodocs.

Would have thought that https://github.com/encode/httpcore/blob/5c045346df52245dbf84fd32f6c0d27a237a0a35/scripts/publish#L4 would have had it covered.

We'll tweak things around in future so that we've got a build step as part of the Test Suite, so that we don't have to wait until the release to see something like that fail.

Still, all good tho. 👍

**Pull request merged**
