### PR TITLE
Version 0.17.2

### PR DESCRIPTION
**Pull request by karosis88**
## 0.17.2 (May 23th, 2023)

- Add `socket_options` argument to `ConnectionPool` and `HTTProxy` classes. (#668)
- Improve logging with per-module logger names. (#690)
- Add `sni_hostname` request extension. (#696)
- Resolve race condition during import of `anyio` package. (#692)
- Enable TCP_NODELAY for all synchronous sockets. (#651)

### CODE REVIEW

**Comment by karosis88** [comment]
Also we can include #662 to this release and resolve https://github.com/encode/httpx/discussions/2635

**Comment by tomchristie** [comment]
> Also we can include https://github.com/encode/httpcore/issues/662 to this release and resolve https://github.com/encode/httpx/discussions/2635

Gotcha - I'll let you lead on this, I'm happy to approve this once youre ready.

**Comment by tomchristie** [comment]
Okay, does this release draft look correct?... https://github.com/encode/httpcore/releases/tag/untagged-21bae35c0de10a5a336f

**Comment by karosis88** [comment]
Let's also put the significant changes at the top, and I believe it's ready.

**Comment by tomchristie** [comment]
> Add https://github.com/encode/httpcore/issues/662. Otherwise, looks correct.

Thanks! I needed to double check that. We've got it listed under PR #668.

> Let's also put the significant changes at the top, and I believe it's ready.

I've updated it in line with your commit https://github.com/encode/httpcore/pull/697/commits/734ba0290ea5f0cce88d7a70db82da27f584b774.

**Review by tomchristie — APPROVED** [review]
seems we're good on this.

**Comment by karosis88** [comment]
Good job!

**Pull request merged**
