### PR TITLE
Remove useless patterns from unasync.py

### PR DESCRIPTION
**Pull request by karosis88**
Some patterns became obsolete, but they were not deleted.

I also included a check for unused patterns.

### CODE REVIEW

**Comment by karosis88** [comment]
Do we need a changelog?

**Comment by tomchristie** [comment]
We don't, no.
It's a tooling change, not a user-facing behavioural change.

**Review by michaeloliverx — APPROVED** [review]

**Comment by Kludex** [comment]
Should we move this to `scripts/`?

**Comment by karosis88** [comment]
I think it's a job for https://github.com/encode/httpcore/issues/638

**Pull request merged**
